# Generated by Django 3.2 on 2021-10-27 07:23

import boardapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('overall_score', models.IntegerField(default=0, validators=[boardapp.models.validate_score])),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='boardapp.gamemaster')),
            ],
            options={
                'unique_together': {('name', 'game')},
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[boardapp.models.validate_score])),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorehistory', to='boardapp.players')),
            ],
        ),
    ]
