# Generated by Django 3.2 on 2021-10-27 07:32

import boardapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('overall_score', models.IntegerField(default=0, validators=[boardapp.models.validate_score])),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='boardapp.gamemaster')),
            ],
            options={
                'unique_together': {('name', 'game')},
            },
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorehistory', to='boardapp.player'),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
    ]
